

CREATE TABLE Utente(
idUtente INT PRIMARY KEY IDENTITY (1,1),
nome VARCHAR(250) NOT NULL ,
cognome VARCHAR(250) NOT NULL,
email VARCHAR(250) NOT NULL UNIQUE,

);

CREATE TABLE Libro(
idLibro INT PRIMARY KEY IDENTITY (1,1),
titolo VARCHAR(250) NOT NULL ,
anno  DATE NOT NULL,
disponibilità BIT
);



CREATE TABLE Prestito(
idPrestito INT PRIMARY KEY IDENTITY (1,1),
dataprestito DATE NOT NULL,
dataritorno DATE NOT NULL,
utenteRIF INT NOT NULL,
libroRIF INT NOT NULL
FOREIGN KEY(utenteRIF) REFERENCES Utente(idUtente) ,
FOREIGN KEY(libroRIF) REFERENCES Libro(idLibro) 
);

SELECT * FROM Utente;